### ISSUE TITLE
Release WebExtensions version

### ISSUE THREAD

**Issue by ExE-Boss** [Ede123/nicermediapages#4]
Since Firefox 57 is now officially out, it might be a good idea to release the WebExtensions version update (maybe also change `strict_min_version` to `57.0a1`, so that those on ESR will get to keep the legacy version, which also supports the chrome:// and about: schemes, as can be seen in #3).

**Comment by Ede123** [comment]
I updated the AMO listing and the update was just approved.

Please test if it actually works as I don't  (and probably never will) have Firefox 57.

Thanks again for the update!

**Comment by ExE-Boss** [comment]
The WebExtension works fine on my end, with the limitations of #3 of course.
